### PR TITLE
Change to i enumerator interfaces for coroutine support

### PR DESCRIPTION
**Pull request by richeso**
Added Unit Tests to the master branch for testing the fixes.

This new branch (Change-To-IEnumerator-Interfaces-For-Coroutine-Support) contains several major changes that is intended for use in Unity's startcoroutine function so as to spread node execution across multiple frames.  

A list of the major changes are as follows:
1. Added BaseNode and BaseParentNode to contain default behavior of nodes. 
2. Added status to track node status as they are ticked  
3. Added NodeMap which contains a dictionary of all Nodes in the tree with name as Key. In this version, it is therefore important to have unique node names otherwise dictionary setup will fail.  
4. Trees and all nodes now implement the IENumerator interface and node status will be passed back  from nodes using yield of the BehaviourStatus. This will enable the tree to hold it's state when it  is ticked and before it has completed it's intended action. The tree can thus be used in Unity's       startcoroutine function so that it can continue where it left off if an action spans more than one frame.
5. Added printTreeAsString to get a visual representation of the tree.  
6. Added methods to set state of all nodes and to retrieve any node by name.  
7. Added 4 unit test classes (TreeBuilderTest1,2,3. and CoroutineTest.testCoroutine)  
8. Added a Randomize Feature to the SelectorNode which will randomize the list of selector leaf nodes  and change the order in which it will tick the selector node in trying to find the first one that  succeeds. (syntax:  .RandomSelector(..) which reuses the selectorNode but with a bool flag to indicate  that selector randomization is required.

### CODE REVIEW

**Comment by ashleydavis** [comment]
Thanks for your contribution. It looks like you have made some good changes. Unfortunately I can't accept your changes that make the behaviour trees library dependent on Unity (and Unity's coroutines). 

It is very important to me that the library remain independent from Unity so it can easily be used with other engines (for example Xna) and also so that it can be unit tested. 

I'll be happy to consider including other changes you have made, but you'll have to remove the Unity specific code. Sorry about that. I hope you are still keen to contribute.

**Comment by richeso** [comment]
No, the changes are not dependent on Unity.. All that's changed is to
enhance the nodes with the IEnumerator Interface which *may be*
 used in Unity's coroutine.. However it is not dependent on it at all.  If
you look closely at the changes, the project is a pure VS studio 2015
project which does not have any Unity imports.

**Comment by ashleydavis** [comment]
Very true! I stand corrected.

But still I'm not sure that I want the IEnumerator change in the base library.

**Comment by richeso** [comment]
No problem. It's totally up to you.

We just needed a way to span the traversal of the tree across more than one
frame in case one or more of the leaf nodes need more time to complete it's
action. This structure provides an easy way for the system to restart a
node at the point it left off.  Of course, if this particular feature is
not required and one iteration of the entire tree can fit into one frame,
one can just tick the tree until it returns success and not have any of the
nodes yield running...

**Pull request closed without merging**
